CREATE TABLE IF NOT EXISTS RULE(
    SENSOR_ID INTEGER PRIMARY KEY,
    RULE_ID INTEGER NOT NULL,
    LOW INTEGER,
    HIGH INTEGER,
    SYMBOL VARCHAR(1) NOT NULL DEFAULT 'C',
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    FOREIGN KEY(SENSOR_ID) REFERENCES SENSOR(ID),
    FOREIGN KEY(RULE_ID) REFERENCES OPERATIONS(ID),
    FOREIGN KEY(SYMBOL) REFERENCES TEMPERATURE_UNIT(SYMBOL)
);

CREATE TABLE IF NOT EXISTS COMPARISON(
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SENSOR(
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    LOCATION TEXT,
    IS_ACTIVE NUMBER(1)
);

CREATE TABLE IF NOT EXISTS TEMPERATURE_UNIT(
    SYMBOL VARCHAR(1) PRIMARY KEY,
    NAME TEXT NOT NULL UNIQUE
);